### ISSUE TITLE
"Commits"

### ISSUE THREAD

**Issue by yenniRamos** [Arquisoft/Trivial1a#4]

**Comment by fjgilgala** [comment]
A mi también me encantaría saber que trabajo "piso" y por supuesto que se consulte el historial de commits, y sobre todo en que horas se realizan muchos de ellos. Que yo sepa desde el primer momento se nos sugirió tener un código común que fuese trabajado entre todos los miembros del equipo y eso yo creo que es lo que se debe hacer. 

A mi no me parece normal estar con una actitud negativa y de falta de respeto continuada hacia mi, y solamente de un a persona, los demás miembros del equipo en ningún momento me han reportado ningún tipo de inconformidad ni tampoco he visto  "Revert commit" sobre un trabajo mal realizado por mi parte, tampoco me lo han reportado en persona. 

No se si yenniRamos es la portavoz del grupo, no lo se, en cualquier caso, como las vías por las que se abrió el conflicto fueron estas estoy en mi derecho de defenderme por este mismo medio y sumarme a la petición de que se revisen mis commits.

Este asunto me parece que sale de unos enlaces a los que modifique su nombre para que este en minúscula como bien los estaban ya otros enlaces, no es por gusto ni por pisar el trabajo de nadie, si no por tener un código homogéneo que se pueda probar, como bien hice en el mismo commit, no me explayaré, que se revise el historial de commits. 

Si cualquier otro miembro del equipo tiene algún otro problema conmigo que me lo reporte de la forma que el vea conveniente yo le contestare, o me defenderé, de la misma forma en actitud y medio.
